USE school;
SELECT * FROM STUDENTS;
INSERT INTO STUDENTS(NAME,GENDER,CLASS,AGE,DATE_OF_BIRTH)
VALUES("RAM","MALE",9,22,"2024-02-01"),
("DIVYA","FEMALE",5,18,"2023-03-01"),
("SHANNU","MALE",6,21,"2023-04-01"),
("RAJ","MALE",5,17,"2023-05-01"),
("SANA","FEMALE",10,16,"2023-06-01"),
("SWATHI","FEMALE",4,20,"2023-07-01");

SELECT * FROM STUDENTS;

-- SELECT ID AND NAME FROM STUDENTS
SELECT ID, NAME FROM STUDENTS;

-- CREATE BAKEUP TABLE FOR STUDENTS
CREATE TABLE STUDENTS_BACKUP_TABLE AS
SELECT * FROM STUDENTS;
DESC STUDENTS_BACKUP_TABLE;
DESC STUDENTS;

-- CREATE A STUDENT INFO TABLE(ID,NAME,CLASS)
CREATE TABLE STUDENT_INFO AS
SELECT ID,NAME AS STDNAME,CLASS FROM STUDENTS;
SELECT * FROM STUDENT_INFO;

-- CREATE TABLE 6 CLASS STUDENT DATA
CREATE TABLE CLASS6 AS
SELECT ID, NAME FROM students
WHERE CLASS=6;

SELECT * FROM CLASS6;

-- CREATE TABLE 7 CLASS STUDENT DATA
CREATE TABLE CLASS7 AS
SELECT ID, NAME FROM students
WHERE CLASS=7;

SELECT * FROM CLASS7;

-- CREATE NEW TABLE STRUCTURE FROM AND EXISTING TABLE STRUCTURE
CREATE TABLE STUDENTS1 AS
SELECT * FROM students
WHERE 1=0;
SELECT * FROM STUDENTS1;

CREATE TABLE STUDENTS2 LIKE STUDENTS;
SELECT * FROM STUDENTS2;

UPDATE STUDENTS
SET AGE = 23
WHERE NAME = 'RAM';

SELECT * FROM STUDENTS; 





