USE school;
DESC STUDENTS;

-- INSERT RECORDS INTO STUDENTS TABLE
INSERT INTO STUDENTS VALUES(101,"MOULI","FEMALE",6,11,"2025-01-01");
INSERT INTO STUDENTS VALUES(101,"MOULI","FEMALE",11,"2025-01-01");

-- APPROCH  2studentsstudents_backup_tablestudent
INSERT INTO STUDENTS(NAME,GENDER,CLASS,AGE,DATE_OF_BIRTH)
VALUES("DINNU","MALE",7,12,"2024-01-01"),
("GETTU","FEMALE",I8,13,"2023-01-01");

-- FETCH TABLE data
SELECT * FROM STUDENTS;

AlTER TABLE STUDENTS DROP COLUMN LOCATION,DROP COLUMN ADDRESS;
DESC STUDENTS;

-- 
DESCRIBE MARKS;
-- INSERTING VALUES FOR MARKS;
INSERT INTO MARKS(STID,S1,S2,S3,PERCENTAGE)
VALUES(101,95,93,94,94.00),
   (102,85,86,87,86.00);
SELECT * FROM MARKS;

-- UPDATE 5 MARKS FOR 101 STUDENT FOR S1 SUBJECT
UPDATE MARKS
SET S1 = S1 + 5
WHERE STID = 101;

SELECT * FROM MARKS
WHERE STID = 101;

--  UPDATE 5 MARKS FOR 102 STUDENT FOR S1 AND S2 SUBJECT
UPDATE MARKS
SET S1 = S1 + 5,
    S2 = S2 + 5
WHERE STID = 102;

SELECT * FROM MARKS
WHERE STID = 102;


-- UPDATE  PERCENTAGE COLUMN  AS DERIVED COLUMN
ALTER TABLE MARKS MODIFY COLUMN PERCENTAGE FLOAT(4,2)
  GENERATED ALWAYS AS((S1+S2+S3)/3) STORED;
  SELECT * FROM MARKS;
  
  -- ADD TOTAL_MARKS COLUMN TO MARKS  TABLE
  ALTER TABLE MARKS  ADD COLUMN TOTAL_MARKS  INT GENERATED ALWAYS AS(S1+S2+S3) STORED AFTER S3;
  SELECT * FROM MARKS;

