-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS MOVIES;

CREATE DATABASE IF NOT EXISTS SONGS;

-- SELECT DATABASE
USE MOVIES;

-- DROP DATABASE
DROP DATABASE IF EXISTS SONGS;

-- SELECT DATABASE
USE MOVIES;


-- CREATE TELUGUMOVIES TABLE
CREATE TABLE IF NOT EXISTS TELUGUMOVIES(
    id INT,
    moviename VARCHAR(30),
    director VARCHAR(30),
    duration INT
);

-- CHECK TABLE
DESCRIBE TELUGUMOVIES;


-- CREATE STUDENT TABLE
CREATE TABLE IF NOT EXISTS STUDENT(
    STDIN INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(30) NOT NULL,
    CLASS INT
);

-- CHECK TABLE
DESCRIBE STUDENT;


-- DROP MARKS TABLE IF EXISTS
DROP TABLE IF EXISTS MARKS;


-- CREATE MARKS TABLE
CREATE TABLE IF NOT EXISTS MARKS(
    STDIN INT,
    S1 INT,
    S2 INT,
    S3 INT,
    PERCENTAGE FLOAT(4,2),
    FOREIGN KEY(STDIN) REFERENCES STUDENT(STDIN)
);

-- CHECK TABLE
DESCRIBE MARKS;


CREATE DATABASE IF NOT EXISTS school;
USE school;

-- student table
CREATE TABLE IF NOT EXISTS STUDENTS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
GENDER VARCHAR(10),
CLASS INT
);

DESCRIBE STUDENTS;

-- ALTER COMMAND OPERATIONS
-- ADD NEW AGE COLUMN
-- SYNTAX: ALTER TABLE TableName ADD COLUMN ColName Datatype [CONSTRAINTS]
-- ADD

ALTER TABLE STUDENTS
ADD COLUMN AGE INT;

DESCRIBE STUDENTS;

ALTER TABLE STUDENTS
ADD COLUMN DATE_OF_BIRTH DATE;

DESCRIBE STUDENTS;


ALTER TABLE STUDENTS
ADD COLUMN LOCATION VARCHAR(50),
ADD COLUMN ADDRESS VARCHAR(30);

DESCRIBE STUDENTS;

-- DELETE COLUMNS
-- SYNTAX: ALTER TABLE TableName DROP COLUMN ColName;
-- DELETE LOCATION AND ADDRESS COLUMNS
ALTER TABLE STUDENTS DROP COLUMN LOCATION,DROP COLUMN ADDRESS;

DESCRIBE STUDENTS;

-- CHANGE ID COLUMN NAME TO STUID
ALTER TABLE STUDENTS RENAME COLUMN ID TO STDID;
DESCRIBE STUDENTS;

-- DELETE COLUMNS
-- SYNTAX: ALTER TABLE TableName DROP COLUMN ColName;
-- DELETE LOCATION AND ADDRESS COLUMNS
ALTER TABLE STUDENTS MODIFY COLUMN GENDER ENUM('MALE','FEMALE');
DESCRIBE STUDENTS;
-- CONVERT CLASS DATATYPE INTO TINYINT
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT UNSIGNED;
DESC STUDENTS;

-- UPDATE CLASS AS NOT NULL
ALTER TABLE STUDENTS MODIFY COLUMN CLASS TINYINT UNSIGNED NOT NULL;

DESC STUDENTS;

DROP TABLE STUDENTS;
 